const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL';

const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
const USER_LOGOUT_REQUEST_SUCCESS = 'USER_LOGOUT_REQUEST_SUCCESS';
const USER_LOGOUT_REQUEST_FAIL = 'USER_LOGOUT_REQUEST_FAIL';

const USER_SAVE = 'USER_SAVE';

const USER_FRIENDS_REQUEST = 'USER_FRIENDS_REQUEST';
const USER_FRIENDS_REQUEST_SUCCESS = 'USER_FRIENDS_REQUEST_SUCCESS';
const USER_FRIENDS_REQUEST_FAIL = 'USER_FRIENDS_REQUEST_FAIL';

const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';

const UserActionTypes = {
  USER_LOGIN_REQUEST,
  USER_LOGIN_REQUEST_FAIL,
  USER_SAVE,
  USER_LOGOUT_REQUEST,
  USER_LOGOUT_REQUEST_SUCCESS,
  USER_LOGOUT_REQUEST_FAIL,
  USER_FRIENDS_REQUEST,
  USER_FRIENDS_REQUEST_SUCCESS,
  USER_FRIENDS_REQUEST_FAIL,
  USER_PROFILE_REQUEST,
};

export default UserActionTypes;
