const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL';

const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
const USER_UPDATE_REQUEST_FAIL = 'USER_UPDATE_REQUEST_FAIL';

const USER_SAVE = 'USER_SAVE';

const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
const USER_LOGOUT_REQUEST_SUCCESS = 'USER_LOGOUT_REQUEST_SUCCESS';
const USER_LOGOUT_REQUEST_FAIL = 'USER_LOGOUT_REQUEST_FAIL';

const UserActionTypes = {
  USER_LOGIN_REQUEST,
  USER_LOGIN_REQUEST_FAIL,
  USER_UPDATE_REQUEST,
  USER_UPDATE_REQUEST_FAIL,
  USER_SAVE,
  USER_LOGOUT_REQUEST,
  USER_LOGOUT_REQUEST_SUCCESS,
  USER_LOGOUT_REQUEST_FAIL,
};

export default UserActionTypes;
